### ISSUE TITLE
Go in MetaCall CLI

### ISSUE THREAD

**Issue by ahmadateya** [metacall/gsoc-2022#2]
I think Go is a good fit for "MetaCall CLI Bootstrapping / Refactor" project

I see a lot of CLI projects based on the Go programming language and I see the language known for its strength in this area

Projects examples:

- [Github CLI](https://github.com/cli/cli)
- [Kubernetes](http://kubernetes.io/)
- [Hugo](https://gohugo.io)
- [Helm](https://helm.sh)
- and [many others](https://github.com/spf13/cobra/blob/master/projects_using_cobra.md)

and also I'd like to contribute to this project in Go in GSoC :smile:

**Comment by viferga** [comment]
@ahmadateya sorry for late reply. We could use Go, you can suggest it in your proposal or PoC. But our main idea is to implement it through bootstrapping.

Basically we want a ultra very small and thin CLI (i.e maybe written with a very few lines of C or C++, maybe Go too, it does not matter) and then all the commands for the CLI and the REPL should be in a folder in code form.

Our idea is to have the possibility to extend completely the CLI without need of recompiling the CLI or having an extra toolset for that.

The CLI would be instead a small plugin based system that loads all the commands from a folder and then launches the CLI or REPL mode with all commands inside.

You can use Go to write this small bootstrapping wrapper but I think C/C++ should be valid too (as it is written in that language already, and the task would be only to remove code and extract some commands from the CLI itself to a folder).

The commands itself cannot be written in Go because we do not support Go from the Loader side, only from the Port side. This means you can use MetaCall API from Go (i.e load TypeScript from Go), but you cannot do the opposite (yet), for example, using Go modules from TypeScript.

**Comment by viferga** [comment]
In the other hand you are free to implement this wrapper in Go and make a proof of concept written in Go where you implement the requirements. We are open to it.
